### ISSUE TITLE
MosSky theme looks out of place for a few applications like Firefox

### ISSUE THREAD

**Issue by swarnendubiswas** [dasnoopy/moslight-themes#11]
I am using MosSky on Ubuntu Gnome 15.04 with gnome3 ppas enabled. The theme is nice overall. But it looks out of place for a few applications like Firefox and Thunderbird.
![screenshot from 2015-04-08 23-08-22](https://cloud.githubusercontent.com/assets/7343807/7059814/a2471962-de44-11e4-9f4e-9ea27f1ce95a.png)

**Comment by dasnoopy** [comment]
Assuming  that MosSky theme is  installed in /usr/share/themes  folder  or in  /home/your_account/.local/share/themes  folder,  it seems that firefox is using the default gtk2 theme...

Do you have the gtk2-engines-murrine package installed?

Regards
Dasnoopy

**Comment by swarnendubiswas** [comment]
Yes, MosSky is in ~/.local/share/themes, and I have the murrine engine installed.

**Comment by dasnoopy** [comment]
If doesn't already exist, you could try to create this symbolic link in **your home** dir :
`$ ln -s .~/.local/share/themes .themes`

Dasnoopy

**Comment by swarnendubiswas** [comment]
Okay, I got it. I had thought that we no longer need ~/.themes, so I had removed it. It seems both ~/.local/share/themes and ~/.themes are required. Thanks.
