### ISSUE TITLE
Scrollbars in Epiphany render with glitches using MosSky

### ISSUE THREAD

**Issue by aperezdc** [dasnoopy/moslight-themes#14]
There are glitches that show up in the Epiphany scrollbars almost always when using MosSky. It looks like the background of the scrollbar is set to transparent and the background is not blended with the web view, and that the scrollbar marker is just painted over and over, without clearing the background.

I took a coupld of screenshots, but I am not sure of the problem can be seen very clearly:

![screenshot from 2015-06-01 13-55-30](https://cloud.githubusercontent.com/assets/723451/7912269/36ab7260-0866-11e5-8ac9-42fcf985aa60.png)

![screenshot from 2015-06-01 14-02-20](https://cloud.githubusercontent.com/assets/723451/7912341/d9a34470-0866-11e5-854b-34b7e180a68a.png)

Sometimes the background of the scrollbars show black instead of white or with old uncleared content, but the black patches never show up in the screenshots.

**Comment by dasnoopy** [comment]
confirmed :-\   ... as you noticed, scrollbars have a transparent background but this cause the issue : it seems to be something related with webkitgtk and the new overlay scrollbars introduced with gtk+ 3.16. As workaround I'll set a white background for scrollbars. Check next commits ;-)

tnks for the bug report..

**Comment by aperezdc** [comment]
@dasnoopy: Thanks! Maybe it is possible to only set the white background for WebKit web views, WDYT? Also, if WebKitGTK+ behaves funnily with transparent scrollbar backgrounds in the theme, probably it is worth it to report the bug upstream.

**Comment by aperezdc** [comment]
I have resported this upstream, too: https://bugs.webkit.org/show_bug.cgi?id=145513

Hopefully there will be some fix in WebKitGTK that will allows to remove the workaround in the future.

**Comment by dasnoopy** [comment]
...in the meantime I'll check, as you suggested, if it is possible set the white background only for webkit.

**Comment by dasnoopy** [comment]
reworked toolbars.

**Comment by aperezdc** [comment]
Neat, I pulled the changes from the Git repo ans things look much nicer. Thanks for fixing this!
