### ISSUE TITLE
Scrollbar issue with multi tabs

### ISSUE THREAD

**Issue by arshavindn** [dasnoopy/moslight-themes#15]
When I open multi tabs in gedit or nautilus... cursor in the edge of screen can't reach to scrollbar, but with one tab it can. May it is a bug?
These images didn't show the cursor but it's in the edge, first image with multi tabs and second one with one tab.
![selection_001](https://cloud.githubusercontent.com/assets/10246162/8038234/870b35da-0e2c-11e5-877d-c9669d53fdf0.png)
![selection_002](https://cloud.githubusercontent.com/assets/10246162/8038235/87137fce-0e2c-11e5-8ff6-acfe9cc3fd2e.png)

**Comment by dasnoopy** [comment]
I can't reproduce it on my system; scrollbars are always reachable in any condition(no tab / a lot of tab.. :-). To be honest I'm working on scrollbars (trying to solve issue #14) but this should not have impact...  
 I could suggest you to use the latest commit and / or try e.g. with the default adwaita theme and see if something change.

**Comment by arshavindn** [comment]
I'm sorry, I'm not good in English. I mean when the windows is maximize, it'll be convinient if cursor in the edge of screen can touch to scroolbar's slider, like in Google Chrome. But with this theme, only when I open one tab, it does and when I open multi tabs, it doesn't.

**Comment by dasnoopy** [comment]
Ok I see the problem and find the root cause.. when you add just one tab , the active tab have a 1px border (file gtk-widgets.css / row : 1128) ; when mouse cursor is on left  over that border scrollbar are not active.. I think I need to review tab and toolbars..check next commits..

**Comment by arshavindn** [comment]
Hope you can make it. Thanks for great themes.

**Comment by dasnoopy** [comment]
Ok just reviewed notebook tabs css code : in the end I removed 1px border from tabs...
