### ISSUE TITLE
No Background color on tooltipps in firefox

### ISSUE THREAD

**Issue by GrizzlySoft** [dasnoopy/moslight-themes#16]
Using MosSky Theme on Fedora 22/Gnome3.16 (nice work by the way..) - there is only one thing which is disturbing me a lot.

The Background on Firefox's menu button tooltipps is transparent and as a result the content not readable...

I will see, if I can figure out the problem myself and keep you updated...

Again, very nice theme

**Comment by dasnoopy** [comment]
Firefox on F22 is compiled using  gtk3 libs. [more info here](https://bugzilla.redhat.com/show_bug.cgi?id=1208888) 
I'll implement soon simple changes in the css code to solve the issue..

Anyway following the

**Comment by GrizzlySoft** [comment]
great, fix confirmed - keep up the great work
