### ISSUE TITLE
Strange dark grey mail preview in Evolution when inactive window

### ISSUE THREAD

**Issue by GrizzlySoft** [dasnoopy/moslight-themes#17]
When Gnome Evolution (Fedora 22 /Gnome 3.16.3) is an inactive window, the frame of mail headers (both: collapsed=full or truncated) breaks out of the design patterns in quite dark grey...

difficult to explain - I mean the recipient/subject info part above the mail body itself...

If this is not a bug but a feature, I will have to live with it ;-)
But since I have not seen this background-color in any other application this is probably not intended...

I even tried to switch the views from "classic" (right bottom frame) to "vertical" (three column) and vice versa, to see if that changes, but the background-color behavior stays that way...

**Comment by dasnoopy** [comment]
with this commit 2ece4e2bead7f87a87842f13e12f7fc6a8f88cef you can find a quick workaround for the issue but I would like to implement better and solution...
