### ISSUE TITLE
Darker text in MosSky?

### ISSUE THREAD

**Issue by tfhavingfun** [dasnoopy/moslight-themes#18]
Hi, I really like the MosSky theme. But can you make texts in titlebar and other places, even throughtout the whole theme a little bit darker? Something like #2c2c2c?

**Comment by tfhavingfun** [comment]
![screenshot from 2015-09-09 23-27-13](https://cloud.githubusercontent.com/assets/3921568/9766206/5baacc9a-574a-11e5-81fa-dbfc5245fb18.png)

**Comment by dasnoopy** [comment]
..to change foreground color to the whole theme  simply try to change __#fg_color__  value in __gtk3/gtk.css__  and the equivalent in __gtk2/gtkrc__  to find a suitable darker text color that fit your needs..

regards
Dasnoopy

**Comment by tfhavingfun** [comment]
@dasnoopy Thanks it worked. I actually tried changing those values before, but I forgot that I need to restart the shell for the changes to happen in gtk2 apps. Again thank you so much! This is my favorite theme for gnome 3.16. I have another question though: how to make the gtk2 header bar consistent with gtk3? I'm talking about the gradient thing in gtk3 that gives the header a bit a depth. For gtk2 it's simply flat.

**Comment by dasnoopy** [comment]
.. with "gtk2 header bar" what do you mean?  the menubar, the toolbar, something else?

**Comment by tfhavingfun** [comment]
![screenshot from 2015-09-11 14-27-29](https://cloud.githubusercontent.com/assets/3921568/9808410/5655ceb4-5891-11e5-9c44-024d011336a5.png)

Sorry I meant the **title bar**

**Comment by dasnoopy** [comment]
Those are two different type of windows : gnome-terminal still use _non-CSD_ style while Nautuils using the _CSD_ style: (https://blogs.gnome.org/fmuellner/2015/01/30/a-small-note-on-window-decorations/ for more details)

for me looks weird  have a big title bar on non-CSD windows (like adwaita default theme does) so I prefer to have non-CSD windows that look like gtk2 apps with a small and flat titlebar

by the way,  as usual you could play with __gtk3/gtk-widgets.css__ file  and change padding values + background image  in this section (line 4193 and below): 

`.titlebar.default-decoration {`
    `padding: 2px 8px 2px 8px; /* top/left/bottom/right */`
   ` border-style: none;`
    `border-color: shade(@toolbar_bg_color, 0.8);`
    `background-image: none;`
    `box-shadow: none;`
`}`

**Comment by tfhavingfun** [comment]
@dasnoopy Thanks. I'll play around with it. One last question though: If I wanted to have inactive(not focused) windows look more different than the active(focused) window, what code would I have to change to achieve that. For example I want texts in the inactive windows look lighter than the active(focused) window?

**Comment by dasnoopy** [comment]
mhh... thank you for pointing that out: really the text color for active/inactive windows is more or less the same! I think I'll do some changes...

In the  meantime , always into the file __gtk3/gtk-widgets.css__,  you can change color value at line 4208 (focused windows) and line 4213 (unfocused windows)

**Comment by dasnoopy** [comment]
__@tfhavingfun__ :  thanks for the patch :)  I think can I close the issue..
