### ISSUE TITLE
gnome terminal buttons in tab bar issue

### ISSUE THREAD

**Issue by arshavindn** [dasnoopy/moslight-themes#23]
I think those buttons need more space between them.
![mozart samsung _010](https://cloud.githubusercontent.com/assets/10246162/10579988/78c80b24-76a5-11e5-9d4c-0a6ae20b9ef1.png)

**Comment by dasnoopy** [comment]
setting `-GtkNotebook-initial-gap: 4>` (instead "0") in gtk-widgets.css / row : 1153, apparently fix the issue..   but I don't want the initial gap ... :-\    ...

**Comment by arshavindn** [comment]
I see why you don't want it. So is there any chance to fix this?

**Comment by dasnoopy** [comment]
... at the moment, I think the only solution / workaround is to set the initial-gap=4 at least 
I checked other themes for gnome 3.18 and  it seems that all of them uses the initial-gap >=4  .. In the meantime I'll check if there's a better solution..
