### ISSUE TITLE
Clicking on the far right of the scrollbar in Firefox doesn't work

### ISSUE THREAD

**Issue by tfhavingfun** [dasnoopy/moslight-themes#26]
**Steps to reproduce:**
With the Firefox browser window maximized and hover your cursor to the far right of the screen and click on the scrollbar and try to drag the it up and down.

The scrollbar simply acts like it's not clicked on, so it won't move at all.

**Comment by dasnoopy** [comment]
thanks for the bug report.. Issue should be gone with the last update.... https://github.com/dasnoopy/moslight-themes/commit/22095edfc9f261258491d2944ab136af35fe9a6c
