### ISSUE TITLE
slider padding in scrollbar

### ISSUE THREAD

**Issue by arshavindn** [dasnoopy/moslight-themes#28]
It's a little bit hard for realizing but the right padding and left padding of slider are not equal. Hope you fix this.
![selection_010](https://cloud.githubusercontent.com/assets/10246162/12231424/e685192e-b889-11e5-8e8b-c3cf3e17f14b.png)

**Comment by dasnoopy** [comment]
The problem seem noticeable only with gnome-terminal  : zooming the image you can notice there isn't a real padding issue : simply, scrollbar have a left dark grey border  (1px) : this cause a weird "optical" effect combined (I think)  with the dark background of gnome-terminal window: [disabling this border](https://github.com/dasnoopy/moslight-themes/commit/8874d32753296a76ffe999760ed3f1a8f8897e6f) only for gnome-terminal solve the issue (css code copied directly from ARC theme ;-) )

Ciao
Dasnoopy
