### ISSUE TITLE
dconf entry issue

### ISSUE THREAD

**Issue by arshavindn** [dasnoopy/moslight-themes#30]
MosCloud theme

![dconf editor_011](https://cloud.githubusercontent.com/assets/10246162/12323178/e3ce3ddc-baeb-11e5-9c4e-921780d2b974.png)

Adtaiwa theme

![dconf editor_012](https://cloud.githubusercontent.com/assets/10246162/12323208/1b92f438-baec-11e5-814f-0a8560c6f015.png)

**Comment by dasnoopy** [comment]
try latest commit https://github.com/dasnoopy/moslight-themes/commit/427cf4fc8b31eb7017acb9b0ea10e9266b735188: adjust padding for treeview.entry widget...
