### ISSUE TITLE
wrong background in Nautilus listview column title

### ISSUE THREAD

**Issue by zeronote** [dasnoopy/moslight-themes#31]
[MosCloud, dark version]
In Nautilus when listview is used, if the mouse goes over the (I don't know how to call it correctly) "column title row", a white background is displayed and text can't be read.

![no_mouse_over](https://cloud.githubusercontent.com/assets/597692/12377142/d535ceba-bd12-11e5-8077-603e7dff3267.png)
![mouse_over](https://cloud.githubusercontent.com/assets/597692/12377143/d53713ce-bd12-11e5-8cb9-e2ca2124d75c.png)

**Comment by dasnoopy** [comment]
tnks for the bug report. fixed background for column header when hovered in normal and dark version...

Ciao
