### ISSUE TITLE
Mosemite makes Chrome sad

### ISSUE THREAD

**Issue by reanimus** [dasnoopy/moslight-themes#6]
Mosemite is probably the best GTK3 theme I've tried out thus far, but Chrome is not at all happy with it. This is what I get when I run Chrome.

![screenshot from 2014-12-03 22 14 24](https://cloud.githubusercontent.com/assets/1053912/5293111/c4ab1814-7b39-11e4-9f76-b278f469644d.png)

Is there any particular reason it breaks to this?

**Comment by dasnoopy** [comment]
I hope issue is solved.. :))

**Comment by dasnoopy** [comment]
I hope issue is solved.. :))
