### ISSUE TITLE
Eclipse window list backgroung is white

### ISSUE THREAD

**Issue by kazysmaster** [dasnoopy/moslight-themes#7]
Eclipse window list background is white and text is light grey which makes it hard to read. Eclipse is using gtk2. Window list is activated via Ctrl-e keyboard shortcut.
![screenshot from 2015-01-14 17 06 01](https://cloud.githubusercontent.com/assets/1195029/5741013/1b39838a-9c11-11e4-9deb-7b7080b26fca.png)

**Comment by dasnoopy** [comment]
Try to comment or delete following lines in the  gtk-2.0/gtkrc file:

  	GtkTreeView::odd-row-color			= mix (0.96, @base_color, @fg_color)
  	GtkTreeView::even-row-color			= "#FFFFFF"

Regards
Dasnoopy

**Comment by kazysmaster** [comment]
Commenting those two lines did really help:
![screenshot from 2015-01-16 12 56 36](https://cloud.githubusercontent.com/assets/1195029/5775213/c6e310c4-9d7f-11e4-89b8-256ccd2ba748.png)
Thanks!
K.

**Comment by dasnoopy** [comment]
Tnx to you for the feedback

Dasnoopy
