### ISSUE TITLE
Mosemite causes gnome-terminal to lose transparency

### ISSUE THREAD

**Issue by fa7ad** [dasnoopy/moslight-themes#8]
Hi, I'm using Mosemite (git version) on Fedora 21
I have all the gtk engines installed.
I can't figure out why Mosemite makes `gnome-terminal` lose its transparency.
Please have a look :smile: 
This is under another theme (*Numix*):
![screenshot from 2015-01-30 01 19 03](https://cloud.githubusercontent.com/assets/7447677/5964437/32932b80-a81e-11e4-8069-1acb40d01e39.png)
And this is under Mosemite:
![screenshot from 2015-01-30 01 21 12](https://cloud.githubusercontent.com/assets/7447677/5964448/57f3f01c-a81e-11e4-81a4-4b39715c7ab2.png)
 The transparency settings don't have an effect either.
Shell version: 3.14.3

**Comment by dasnoopy** [comment]
I installed gnome-terminal with transparency patch from AUR and Numix theme (from git) on my Archlinux system but  sometime, starting gnome-terminal  I lose transparency also with numix 

Then I installed other gtk3 themes like zukitre or vertex and same behaviour : most of the time gnome-terminal start without transparency : the odd thing is that changing theme  on the fly with gnome-terminal still open, the transparency works (also with mosemite) 

I'll try to investigate :)

Which graphics driver do you use? Mine are noveau open drivers with a NVIDIA GT9800 card

regards
Dasnoopy

**Comment by fa7ad** [comment]
I use radeon FOSS drivers.

**Comment by dasnoopy** [comment]
Ok btw shouldn't a graphic driver issue: in fact, with Adwaita theme  patched gnome-terminal start always with transparency ... Try latest commit  and let me now  :-)

**Comment by fa7ad** [comment]
Its working, sorry i didnt comment earlier. its a bit buggy at times though.
