### ISSUE TITLE
Rhythmbox buttons

### ISSUE THREAD

**Issue by ilpillo** [dasnoopy/moslight-themes#9]
I think there is an issue with Rhythmbox repeat and shuffle toggle buttons, as you can see from the two pictures there is almost no difference between the pressed and not pressed state. (just a thin black border)

shuffle not pressed:
![shuffle depressed](https://cloud.githubusercontent.com/assets/10895560/6881003/11c8a6f4-d54c-11e4-87e9-cdfa8e12799f.png)

shuffle pressed:
![shuffle pressed](https://cloud.githubusercontent.com/assets/10895560/6881004/18dbee38-d54c-11e4-958e-dbe59904b29b.png)

**Comment by dasnoopy** [comment]
thanks for report the issue

Think should be ok with latest commit.  https://github.com/dasnoopy/moslight-themes/commit/c8b1998503bc695797bf29cec1ce8bbbdcedadd4

regards

**Comment by ilpillo** [comment]
Ok, Mosemite is fixed now but MosLight is still broken :)
thanks
